application: join-event-barcamp-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- appstats: on

libraries:
- name: django
  version: latest
  
handlers:
- url: /(.*)
  script: main.application

  


